# -*- coding: utf-8 -*-
"""rakeshsingh

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zHUBdoe3ubjLC6tZFKc1pwYR6BF1uZG-
"""

print("nirdeh kumar")

print (4+4)

x=4
print(float(x))

i=0
while i<5:
    print(i)
    i+=1
    if(i==3):
        pass
        print("aman")



i=0
while i<6:
    print(i)
    i+=1
    print("rakesh")
    if(i==4):
        break


i=2
while i<10:
    print(i)
    i+=1
    if(i==7):
        print("nirdesh")
        continue

x="rakesh"
print(x.upper())

i=0
for x in range (10):   # for loop in int
    print(i)
    i=i+1
    if(i==5):
        print("rakesh")
        break            #pass/continue/break

x =["98","99","97","95","96"]
for i in x:

    print(x)

students = [ "rakesh" ,"nirdesh","aman","ankur","sanjay","pandey"]
for student in students: # there are using break and continue.
    if student == "aman":
        continue;
    print(student)

students = ["rakesh","nirdesh","aman","ankur","sanjay","pandey"]
for student in students:
    if student == "sanjay":
        break;
        print(student)

x ="Hello world!"

 print(x.replace("H","J"))

age=20
if age >= 18:# here we are using if else condition.
    print ("You are adult")
    print ("You are rakesh")
elif  age < 18 and age >4:
        print ("You are in college")
else:
        print ("You are a child")

        print ("thank you so much")

age = 26
txt = "my name is rakesh,and i am {} "# here are using format string.
print (txt.format(age))

quantity=3                                                                                  #note {} braces
item =56
price =50.5
myorder ="i want {} piece of item{} for {}dollars"# we are using format string.
print (myorder.format(quantity,item,price))

x =["rakesh", "nirdesh", "aman", "ankur", "sanjay"]
 print(x)

print("twinkle,twinkle,little star.\n\t how  I wonder what you are!\n\t\t up above the world so high.\n\t\t like a diamond in the sky,\n twinkle ,twinkle, little star.\n\t how i wonder what you are! ")

import datetime
 x = datetime.datetime.now()
 print ("current date and time:",)
 print (x.strftime(" %Y-%m-%d %H:%M:%S "))

import sys
print ("python version")
print (sys.version)
print ("python info.")
print (sys.version_info)

values = input("input some coma separated number:")
list = values.split(",")
tuple=tuple(list)
print ('list : ',list)
print ('tuple :', tuple)

import datetime
x = datetime.datetime.now()
print (x.strftime("%Y-%m-%d  %H:%M-%S"))

list =  ['3','5','7','23']
 tuple  = ('3','5','7','23')
print(list)
print (tuple)

for x  in "appllerakesh":
   # if x == "r":
        #break
        print(x)

from math import pi
r = float(input ("Input the radius of the circle : "))
print ("The area of the circle with radius " + str(r) + " is: " + str(pi * r**2))

print ("hello world")

def near_thousand(n):
      return ((abs(1000 - n) <= 100) or (abs(2000 - n) <= 100))
print(near_thousand(1000))
print(near_thousand(900))
print(near_thousand(800))
print(near_thousand(2200))

pi=3.14
r=6.0
V=4.0/3.0*pi*r**3
print("the sphere of the volume:",V)

pi=3.14
r=6.0
A=pi*r**2
print("area of the circle:",A)

def new_string(str):
  if len(str) >= 2 and str[:2] == "Is":
    return str
  return "Is" + str

print(new_string("Array"))
print(new_string("IsEmpty"))

print('rakesh','nirdesh','aman',end= ' ankur') #in this case we add any object inthe last

print('rakesh' ,'nirdeh' ,'aman', sep=' pandeyji ') #in this case we add any object between two object

color_list_1= set(["White", "Black", "Red"])
color_list_2= set(["Red" ,"Green"])
print("Original set elements:")
print(color_list_1)
print(color_list_2)
print("\nDifferenct of color_list_1 and color_list_2:")
print(color_list_1.difference (color_list_2))
print("\nDifferenct of color_list_2 and color_list_1:")
print(color_list_2.difference (color_list_1))

color_list_1 = set(["White", "Black", "Red"])
color_list_2 = set(["Red", "Green"])
print("Original set elements:")
print(color_list_1)
print(color_list_2)
print("\nDifferenct of color_list_1 and color_list_2:")
print(color_list_1.difference(color_list_2))
print("\nDifferenct of color_list_2 and color_list_1:")
print(color_list_2.difference(color_list_1))

b=int (input("input the base:"))
h=int(input("input the height:"))
area=1/2*b*h
print(area)

x=4
y=3
z=(x+y)*(x+y)
print(z)

amount=10000
rate=3.5
year=7                         #P(1+r/100)nt
print(amount*(1+(0.01*rate))**year)

numbers = [
    386, 462, 47, 418, 907, 344, 236, 375, 823, 566, 597, 978, 328, 615, 953, 345,
    399, 162, 758, 219, 918, 237, 412, 566, 826, 248, 866, 950, 626, 949, 687, 217,
    815, 67, 104, 58, 512, 24, 892, 894, 767, 553, 81, 379, 843, 831, 445, 742, 717,
    958,743, 527
    ]

for x in numbers:
    if x == 237:
        print(x)
        break
    elif x % 2 == 0: # note here we are using modulus because which no divided by 2
     print (x)

l=[3, "ABC", 'x-y-z']
a =''.join(str(l))
print(a)

set={"rakesh" ,"nirdesh" ,"aman"}
print(set)                          # set statement

set = {"rakesh", "nirdeh", "aman", "rakesh"}   #set is only allow original items and duplicate item set also ignored
print(set)

set = {"rakesh", "nirdeh","aman" ,"ankur"}  #set len function
print (len(set))

set1={"rakesh", "nirdesh", "aman"}
set2={1,5,7,9,3}                        # set function data type
set3= {True ,False ,False}
print(set1)
print(set2)
print(set3)

set={"abc" ,34 ,"True" ,40 ,"male",40}
print(set)                                  #{}dictionary symbol # {} is set symbol

tuple=("rakesh", "nirdesh","rakesh", "aman")
print(tuple)                                 #tuple has no changed duplicate item ()

dict={"rakesh", "nirdesh", "aman", "rakesh"}   #{} dictionary symbol
print(dict)                                   # dictionary also changed duplicate item

list=["rakesh", "nirdesh", "aman" ,"rakesh"]  # list has no changed duplicate item []
print(list)

set={"rakesh", "nirdesh", "aman" ,"ankur"}
for i in set:                             # forloop use in set
    print(i)

set={"rakesh", "nirdesh", "aman", "nirdesh"}  #check the item in set function
print("rakesh" in set)
print(set)

set={"rakesh" ,"nirdesh" ,"aman"} #add any item in set function
set.add("ankur")
print(set)

set={"rakesh", "nirdesh", "aman"}        #update element from set into tropical
tropical={"ankur", "pandey", "prashant"}  # not same like add function
set.update(tropical)
print(set)

set={"rakesh", "nirdesh", "aman"} # another war to update any item in the set
mylist={"ankur"}
set.update(mylist)
print(set)

a=input()     # split function
l=a.split('-')
print(l)

l=['3', '4']
a="".join(l)     #join function
print(a)

set={"rakesh", "nirdesh", "aman"}
set.remove("aman")                # remove function
print(set)

set={"rakesh", "nirdesh", "aman"}
set.discard("nirdesh")           # discard function
print(set)

set={"rakesh", "nirdesh", "aman"}
x=set.pop()
print(x) # remove item
print(set) # the set after removal

set={"rakesh", "nirdesh", "aman"}
set.clear()
print(set)                      #clear all element

set1={"rakesh", "nirdesh", "aman"}
set2={"ankur", "pandeyji"}
set3=set1.union(set2)
print(set3)                       # union function same as update function

dict={"rakesh" ,"nirdesh", "aman", "rakesh"}
print(dict)    #dict also changed duplicate item

list = [1,3,6,7,9,4,2,5]    #note
print(list[-1:-6:-3])
print(type(list))

list=[1,2,3,4,5,6,7,8]
print(list[1:-4:2])
#print(range(list))

a=8
print(id(a))
a=9
print(id(a))
print(a) # int data is immutable because it doesn't allow
l=[4,5,6]
print(l)
print(id(l))
l[1]=9
print(l)
print(id(l))   # list is mutable because it allow to change

# list vs tuple
tuple=(2,4,6)
print(tuple)
print(id(tuple))
list=[2,4,6]
print(list)
print(id(list))
dict={2,4,6}
print(dict)
print(id(dict))

list = ['a','b','c','d','e','f','g','h','i']
list[1:4]=[8,9,6]
print(list)
print(len(list))
print(list[3:-5:2])
del list[:4]
print(list)

tuple=(2,4,6,8)
print(tuple)
print(id(tuple))
a=5                                                  # float,int,bool are immutable objects
print(a)                                             # note-all function like string,tuple,int,float,bool are immutables.
print(id(a))
str="rakesh"
print(str)
print(id(str))

list=[2,4,6,8]
print(list)
list[2]=9
print(list)
print(id(list))
dict={2,4,6,8}
print(dict)
dict.add(1)
print(dict)         # all function like as--dict,list and set are mutable function
print(id(dict))
set={2,4,6,8,9}
print(set)
set.add(1)
print(set)
print(id(set))

str="rakrsh"
print(id(str))
str="rakesh"
print(id(str))
list=[1]
print(id(list))
list=[1]
print(id(list))

txt="rakesh kumar";      # string methods
x = txt.capitalize()
print(x) # capitalize
txt="RAKESH KUMAR";
x=txt.casefold()
print(x) #casefold
txt="rakesh kumar";
x=txt.center(30)
print(x) # center
txt = "rakesh kumar kumar";
x=txt.count("kumar")
print(x) #cunt
txt= " I am rakesh kumar";
x=txt.encode()
print(x) # encode

age=int(input())
if(age>=20):
    print("Eligible to voting")
elif(age<=18 and age<=16):
    print("Not eligible to voting")
else:
    print("they also eligible to voting")

math=int(input())
if(math>=90):
    print("scholar")
elif(math>=80 and math<90):
    print("done well")
elif(math>=70 and math<80):
    print("can do better")
else:
    print("not qulified")

for j in range(1,6,2): #not understood
    print(j)

a=int(input())
if(a==8):
    print("yes")
elif(a==9):
    print("edy")
else:
    print("Edyoda")

rollno=int(input())
ctry=input()
if (rollno>0):
    if(ctry == "INDIA"):
        print("yes")
    else:
        print("inner else")
else:
    print("outer else")

marks=int(input("enter your marks"))
if(marks>=90):
        print("grade A")
elif(marks>=80 and marks<90):
        print("grade B")
elif(marks>=70 and marks<80):
        print("grade C")
elif(marks>=60 and marks<70):
        print("grade D")
else:
        print("reattemt")

a=5
for  i in range(2,8):
    #a=a+1
    print(a)
    a=a+1

i=0
l=[9,4,5]
for a in l:
    i=i+1
    print(i,)

for i in range(1,7):
    if(i==4 or i==2):
        continue
    print(i)

l=[3,4,5]
for i in range(len(l)):
    print(l[i])


for i in l:
        print(i) #repitation of process iterable


tuple=(3,4,5)
for i in range(len(tuple)):
    print(tuple[i])

for i in  tuple:
    print(i)

s="Edyoda"
for i in range(len(s)):
        if (i==2):
            continue/break
        print(s[i])

d={1:2,8:3,4:5,7:8}
for i in d.keys():
    print(i) # for keys



d={1:2,8:3,4:5,7:8}                                 #iterables
for i in d.values():
    print(i)  # for values



d={1:2,8:3,4:5,7:8}
for i,j in d.items():
    print("keys",i,"values",j)   # for items

d={1:2,8:3,4:5,7:8}
for i in d:
    d[8]=9
    print(i,d[i])

maths=int(input())
phy=int(input())
if (maths>40):
    if(phy>40):
        print("passed in maths and phy")
    else:
        print("passed in maths but not in phy")
else:
        print("not passed in maths but dont know in phy")

n=int(input())
if(n%2!=0):
       print("weird")
elif(n%2==0 and n in range(2,6)):
       print("not weird")
elif(n%2==0 and n in range(6,21)):
       print("weird")
elif(n%2==0 and n>0):
       print("not weird")

test_str="geeksforgeeks 33 best"
print(len(test_str))
c=0
for i in test_str:
    if(i==" "):
        continue
    else:
        c=c+1

print(c)


c=0
for i in test_str:
    if(i!=" "):   #counting space variable
        continue
    else:
        c=c+1

print(c)

s="Edyoda"
print(len(s))
i=int(input())
n=""
for j in range(len(s)):
    if(i==j):
          pass
    else:
        n=n+s[j]
        print(id(n))


print(n)

s1="ED"
s2="Yoda"
print(id(s1))
print(id(s2))
a=s1+s2
print(id(a))
print(a) #string concatenation

s="100101010"
#i=int(input())
f=0
for i in s:
    if(i!="1" and i!="0"):
          f=f+1
else:
    pass
    print(f)
    if(f>0):
        print("not a binary string")
    else:
         print("binary string")

l1=[2,3,4,5]
l2=[3,4,7,6]
a=[]
for i in l1:
    if i in  l2:
        pass
    else:

        a.append(i)

print(a)

l=[9,8,7,6]
i=int(input())
j=int(input())
a=[]
a=l[i]
l[i]=l[j]
l[j]=a
print(l)    # swap condition
print(len(l))
print(a)

s="I study from Edyoda"
lw=s.split(" ")
a=[]
for i in lw:
    if(len(i)%2==0):
        a.append(i)
    else:
        pass
print(a)

s="Viratkohlirakesh"
print(len(s))
n=""
for i in s:
    if i in n # if condition check to local variable
        pass
    else:
        n=n+i  # this condition add both values of i and n than after remove same items
print(n)
        # print(id(n))

s1="listen"
s2="silent"
if(set(s1)==set(s2)):
    print("Anagram")
else:
        print("not Anagram")






s1="listen"
s2="silent"
n=""
for i in s1:
    if i in s2:
        n=n+i
else:
     pass
if(s1==n):


    print ("Anagram")

s1="asdf"
s2="fdsa"
n=""
if(len(s1)==len(s2)):
    for i in s1:
        if i in s2:
                print("Anagram")
                break
        else:


              #break # if remove this break condition than after print only "anagram"

               print("not Anagram")

a="hello, world!"#split program.
b=a.split(",")
print(b)     #with the help of split we can divide any string in two parts.


a="hello" #concatenation program.
b="world"
c=a+b
print(c) #where we add or merge two variables than we use concatenation.


 #where we can  not add numbers or strings that where we use format.

age=25
height=5.9
str= "my name is rakesh and i am {} years old  and my height is {}  and i am from rampur"
print(str.format(age,height)) # format program





txt="Apple"
print(txt.isidentifier()) # isidentifier where we use when we identifie the spelling

s="hello geeks for geeks is computer science portal"
print(len(s))
txt=s.split(" ",maxsplit=4)
print(txt)

import math
print(math.pi)


print(math.factorial(6))

l=["", "hey", ""]
a=[]
for i in l:
    if i in l:
        a.append(i)
print(a)

num=int(input())
count_even=0
count_odd=0
l=[]
for i in range (1, num + 1):
    l.append(i)

    if int(i) % 2 == 0:
        count_even=count_even+1
    else:
        count_odd=count_odd+1

print(l)
print("number of even numbers:" ,count_even)
print("number of odd numbers:",count_odd)

num=int(input())
count_even=0
count_odd=0
if num % 2 == 0:
    count_even=count_even+1

else:

    count_odd=count_odd+1


print("number of even numbers:" ,count_even)
print("number of odd numbers:",count_odd)

num=1,2,3,4,5,6,7,8,9
count_even=0
count_odd=0
for i in num:
    if i % 2 == 0:
        count_even=count_even+1

    else:

        count_odd=count_odd+1


print("number of even numbers:" ,count_even)
print("number of odd numbers:",count_odd)





n=int(input("Enter a number:"))
l=[]
for i in range(n):
    a=int(input())
    l.append(a)


print(l)







n=int(input())
even=0
odd=0
for i in range(n):
    if i%2==0:
        even=even+1
    else:
        odd=odd+1

print("number of even numbers:" ,even)
print("number of odd numbers",odd)

str="Edyoda"
print(str[::-1])

fib=0,1,2,3,5,8,13,21
a=1
b=1
print(a)
print(b)

for i in range(9):

            c=a+b
            a=b
            b=c
            print(c)

str="Edyoda"
n=0
n=" "
for i in str:
    if i in n:
        pass

    else:
        n=n+str[::-1]

print(n)

st="Edyoda"
print(len(st))
i=0
while i<=0:
       i=i+1
print(st[::-1])

#string operation
st="rakeshkumar SINGH"
t=st.capitalize()
print(t)

st="rakesh is good"
t=st.center(20,'*')
print(t)

st="RaKesHkuMaR"
t=st.casefold()
print(t)

st="rakesh 12333445kumar"
t=st.count("kumar")
print(t)
t=st.count("4")
print(t)


st="rakesh kumar"
t=st.endswith("r")
print(t)


st="rakesh\t123\tkumar\t@#$"
t=st.expandtabs()
print(t)



st="rakesh#@12python34 program"
t=st.encode()
print(t)

st="rakesh kumar"
t=st.find("r")
print(t)



st="rakesh kumar"
t=st.rfind("g")
print(t)



st="Edyoda"
print(st.index("d"))
print(st.rindex("a"))

import datetime
x=datetime.datetime.now()
print(x.strftime("%Y-%m-%d   %H:%M:%S"))



from datetime import datetime
now=datetime.now()
current_time= now.strftime("%H:%M:%S")
print("current time:",current_time)


from datetime import datetime
import pytz

tz_NY = pytz.timezone('America/New_York')
datetime_NY = datetime.now(tz_NY)
print("NY time:", datetime_NY.strftime("%H:%M:%S"))

tz_London = pytz.timezone('Europe/London')
datetime_London = datetime.now(tz_London)
print("London time:", datetime_London.strftime("%H:%M:%S"))




from pytz import timezone
from datetime import datetime
timezone="Himachalpradesh/Kolkata"
india_time = datetime.now()
print(india_time.strftime('%Y-%m-%d %H:%M:%S.%S'))

num=int(input("Enter number:"))
if num%2==0:
    print("enen num:", format(num))
else:
    print("odd num:",format(num))

st="rakesh"
print(st.zfill(8)) #it is use to add and num,char etc from the left side



st="Edyoda"
print(st.strip("E")) #removing the char from the leftside


st="rakesh"
print(st.rstrip("h")) #removing the char from the right side


st="Edyoda"
lenght=7
fillchar="*"
print(st.center(22)) # it shifted to right side


st="Edyoda"
lenght=8
fillchar="*"
print(st.rjust(lenght,fillchar)) # it just call right allignment (right shift)
print(st.ljust(lenght,fillchar)) # lefth shift
print(st.rjust(8,"@"))
print(st.ljust(10,"&"))

st="rakesh"
print(st.split("h")) # removing the char

st= "rakesh is very good boy"
print(st.partition("very")) #it just devided the paragragh in part


st="Edyoda"
print(st.replace("E","R")) #it just replace the char

a=input()
l=a.split(",")
print(tuple(l))  #int value conveted into tuple


a=int(input("Enter now large list is required:"))
b=[]
for i in range(a):
    c=int(input("Enter the elements:"))
    b.append(c)
    print(b)
for i in b:
    if(i<5):

        print(i)

tuple=(2,3,4,"rakesh","Edyoda")*2
print(tuple) # inthe tuple multiplication

def greet(name, msg,age):
    """This function greets to
    the person with the provided message"""
    print("Hello", name + ', ' + msg, ','+ age)

greet("Monica", "Good morning!",'25')

def f(x):
    def f1(*args, **kwargs):
        print("Sanfoundry")
        return x(*args, **kwargs)
    return f1

import sys
print("python version")
print(sys.version)
print("version info")
print(sys.version_info)

def last(n):
    return n[-1]

def sort_list_last(tuples):
    return sorted(tuples, key=last)

print(sort_list_last([(2, 5), (1, 2), (4, 4), (2, 3), (2, 1)]))

l1=[[1,2,3],[4,5,6]]
l2=[]
for i in l1:
    l2.extend(i)

print(l2)

x = dict()
for i in range(97,123):

    x[chr(i)]=i
print(x)

print(ord(input("")))

char=input("enter number:")
ascii=ord(char)
print(char,ascii)

n=int(input("Enter the element:"))
dict={}
for i in range(n):
    k=input("enter key:")
    v=input("enter value:")
    dict.update({k:v})

print(dict)

tuple1 = [(2, 5), (1, 2), (4, 4), (2, 3), (2, 1)]
L2 =[]
L3 =[]
for i in tuple1:
    L2.append(i[1],)
    L2.sort()

print(L2)
for l in L2:
    for n in tuple1:
        if l==int(n[1],):
            L3.append(n)

print(L3)

tuple1 = [(2, 5), (1, 2), (4, 4), (2, 3), (2, 1)]
list2=[]
list3=[]
for i in tuple1:
    list2.append(i[1],)
    list2.sort()
    print(list2)
for l in list2:
        for n in tuple1:
             if l==int(n[1],):
                list3.append(n)
                print(list3)

def greet(a):
    for i in a:
        print("hello!Nirdesh",i)
        print("this is rakesh")

l=["what happend","why are  you calling me"]
greet(l)

def d(a,b):
    result=a+b
    return result
    print("All good")
c=d(2,3)
print(c)
e=d(13,23)
print(e)

def add(a,b):
    c=a%b
    return c

x=int(input())
y=int(input())
sum=add(x,y)
print(sum)

#function to find average mark
def find_average_marks(marks):
    sum_of_marks=sum(marks)
    total_subjects=len(marks)
    average_marks=sum_of_marks/total_subjects
    return average_marks


#calculate the grade return it
def  compute_grade (average_marks):
    if average_marks >= 80:
        grade="A"
    elif average_marks >= 70:
        grade="B"
    elif average_marks >= 60:
        grade="C"
    else:
        grade="D"
    return grade

marks=[67,88,99,65,77]
average_marks=find_average_marks(marks)
print("your average marks is:",average_marks)

grade=compute_grade(average_marks)
print("your grade is:", grade)

x = 50
def func(x):
    print('x is', x)
    x = 2
    print('Changed local x to', x)
func(x)
print('x is now', x)

x = 50
def func():
    global x
    print('x is', x)
    x = 2
    print('Changed global x to', x)
func()
print('Value of x is', x)

def say(message, times = 1):
    print(message * times)

say('Hello')
say('World'"\t",15)

def func(a, b=5, c=10):
    print('a is', a, 'and b is', b, 'and c is', c)

func(3, 7)
func(25, c = 24)
func(c = 50, a = 100,)


def maximum(x, y):
    if x > y:
        return x
    elif x == y:
        return 'The numbers are equal'
    else:
        return y

print(maximum(4, 3))

def cube(x):
    return x * x * x
x=cube(3)
print (x)


y = 6
z = lambda x:x * y
print (z(8))

# lambda definition does not include a return statement. it always contains an expression which is returned.
lamb = lambda x: x ** 3
print(lamb(5))

# Any change made in to an immutable data type in a function isn’t reflected outside the function.
i=0
def change(i):
   i=i+1
   return i
change(1)
print(i)


# The statement “global b” allows the global value of b to be accessed and changed.
a=10
b=20
def change():
    global a
    a=45
    b=56
change()
print(a)
print(b

def change(i = 1, j = 2):
    i = i + j
    j = j + 1
    print(i, j)
change(j = 1, i = 2)


def display(b, n):
    while n > 0:
        print(b,end="")
        n=n-1
display('z',3)



def a(b):
    b = b +[5]

c = [1, 2, 3, 4]
a(c)
print(len(c))

def evenodd(a):
    if a%2==0:
        print("even number",a)
    else:
        print("odd number",a)
m=int(input("enter a number:"))
evenodd(m)

def multiply(numbers):
    total = 9
    for x in numbers:
        total *= x
    return total
print(multiply((8, 2, 3, -1, 7)))



def mult(a,b,c,d,e):
     return a+b*c-d/e
mult1 = mult(8, 2, 3, -1, 7)
print(mult1)

ints = [8, 23, 45, 12, 78]
for id, key in enumerate(ints):
    print(id, key)

def string(string1):
    rev_str=" "
    for i in string1:
        rev_str = i+rev_str

rev_str=input("enter string:")
string(rev_str)
print(rev_str[::-1])




def string(string1):
    rev_str=" "
rev_str=input("enter string:")
string(rev_str)
print(rev_str[::-1])

def string(x):
  return x[::-1]
  txt= string("1234abcd5")
  print(txt)

list1=[1,2,3,3,3,3,4,5]
list2=[]
for i in list1:
    if i not in list2:
        list2.append(i)

print(list2)



for x in range(0,7):
  if(x==6 or  x==3 or x==0):
      pass
  else:
      print(x)

def add_list(a,b,c,d,e):
     sum=a+b+c+d+e
     return sum
add=add_list(8,2,3,0,7)
print(add)

str="The1234 quick@&$ Brow Fox"
upperc=0
lowerc=0
digitc=0
specialc=0
for x in str:
    if x.isupper():
        upperc+=1
    elif x.islower():
            lowerc+=1
    elif x.isdigit():
            digitc+=1
    else:
        specialc+=1

print("The quick Brow Fox:",str)
print("No.of uppercase characters:",upperc)
print("N0 of lowercase characters:",lowerc)
print("special characters:",specialc)
print("digit count:",digitc)



def string1(s):
    d={"upperc":0, "lowerc":0}
    for x in s:
        if x.isupper():
           d["upperc"]+=1
        elif x.islower():
           d["lowerc"]+=1
        else:
           pass
    print ("Original String : ", s)
    print ("No. of Upper case characters : ", d["upperc"])
    print ("No. of Lower case Characters : ", d["lowerc"])

string1("The quick Brown Fox")

